### ISSUE TITLE
Luma crashes when generating randomizer

### ISSUE THREAD

**Issue by menyas** [gamestabled/OoT3D_Randomizer#123]
New 2ds XL
Firmware ver. 11.14.0-46U
Luma v10.2.1

No matter how many times I try, I always get this error when hitting to start generating the rando.
![20210416_154319](https://user-images.githubusercontent.com/66636381/115069916-a85a3a80-9eca-11eb-95c1-2c2b8de19e03.jpg)
I've also tried disabling arm11 handlers on the Luma menu, but then the console just straight up reboots.

**Comment by M-1-RLG** [comment]
Are you using the USA version of Ocarina of Time 3D?

**Comment by leggettc18** [comment]
I could be wrong but I feel like the version he has wouldn't matter for the patch generation step right? I'd imagine that the only thing having the wrong version would do is make the patch not apply when he starts the game.

**Comment by Icing-weaponry** [comment]
I have the same issue on my end

New 3ds
Firmware ver. 11.14.0-46J
Luma v10.2.1
OOT3d version NTSC ID 0004000000033500

I changed OOT locals using local switcher to english/US but still get that issue

Let me know if you need the luma log

**Comment by gamestabled** [comment]
Is it possible your SD card is out of space or read only or something? The app needs to be able to write some new files on the SD card

**Comment by Icing-weaponry** [comment]
the SD card still has 20 Gb of free space and no it isn't in read only unfortunately

**Comment by DZTSKR** [comment]
try using the v1.1.1 version instead of nightly, it worked for me

**Comment by Icing-weaponry** [comment]
it worked! thank you

**Comment by SonicFreax** [comment]
Hey so I just got the rando a few nights ago and it just started crashing when i launch the game what should i do there is no helpful youtube vid about this subject also should i post a pic?
