### ISSUE TITLE
Minor text bug? "OK" text from Deku Scrubs replaced with "BOK"

### ISSUE THREAD

**Issue by leggettc18** [gamestabled/OoT3D_Randomizer#128]
Pretty much what the title says. Obviously this is like, the lowest priority imaginable, but I didn't see it mentioned anywhere so I thought I'd make an issue. I generated a seed with v1.1.1. Everything seems to be perfectly fine otherwise, but the "OK" option when talking to Deku Scrub Merchants seems to be replaced with "BOK". It doesn't seem to cause any other adverse effects after having played a few hours in and beaten a few dungeons. I'm at work right now but I can attach a spoiler log (or at least copy-paste the settings from it) later tonight if desired.

**Comment by cjohnson57** [comment]
Thanks for the report, this is a known issue, should hopefully be fixed in the next release, although it's pretty funny.

**Comment by leggettc18** [comment]
Ok, yeah I figured someone had seen it before, I even looked for a commit message saying it was fixed, but I didn't see anything so wanted to be sure. Definitely had me chuckling a bit to be sure! Odd the places random bugs can show up from time to time huh? Guess we can close the issue then.
