### ISSUE TITLE
MQ Jabu unbeatable

### ISSUE THREAD

**Issue by Kevok93** [gamestabled/OoT3D_Randomizer#131]
In the forked-path room leading up to the three electric tentacle rooms, there is a blue (held) switch blocking access to the central tentacle. Normally, you're supposed to take a small crate from one of the other paths, and leave it on the switch. The crates do not seem to spawn, blocking entrance to the final tentacle and preventing completion of the dungeon.

**Comment by gamestabled** [comment]
It turns out that box wont appear in MQ Jabu if the world isnt mirrored, its a bit silly. We will fix it for the next release. In the meantime, you can do the same trick shown here: https://youtu.be/un7vIx6hfP4?t=5798

thanks for reporting this

**Comment by gamestabled** [comment]
fixed in latest nightlies thanks to #136 
will be included in any future releases
