### ISSUE TITLE
Error When going to Death mountain trail

### ISSUE THREAD

**Issue by KHMaple** [gamestabled/OoT3D_Randomizer#135]
Processor: Arm11 (Core 0)
Exception Type: data abort
Fault Status: Translation - Section
Current Process: CtrApp (000400000033500)
I'm using the USA version but I got a Japanese 3DS
The CIA works fine normally but whenever I run the randomizer I get the error specifically trying to enter Death mountain after showing Zeldas letter to the guard.
![20210426_115300](https://user-images.githubusercontent.com/83244390/116137460-94b88c00-a6a1-11eb-8b6a-1fa00118d0b7.jpg)

**Comment by cjohnson57** [comment]
Thank you for the report, can you post your spoiler log? If not, then just what version of the randomizer you're using.

**Comment by KHMaple** [comment]
> Thank you for the report, can you post your spoiler log? If not, then just what version of the randomizer you're using.

I don't have the spoiler logs cause I was going through a lot while testing a bunch of different solutions but i'm using version 1.1.1, it turns out re-randomizing it worked,  and i'm not having any issues with the new one, so I don't know what with wrong during the first one.
