### ISSUE TITLE
Crashes on Nightly-3d193b8a01b5d61089ff8a973602a7565c58835f

### ISSUE THREAD

**Issue by ZeldaLover227** [gamestabled/OoT3D_Randomizer#141]
The randomizer crashes in both it’s app and homebrew forms a few secounds after it reaches writing patch.

**Comment by gymnast86** [comment]
Would you be able to upload your CHACHED_SETTINGS.xml and CACHED_COSMETICS.xml files here (found in /3ds/presets/oot3dr/settings and /3ds/presets/oot3dr/cosmetics respectively) as well as a crash screen? That'll help us pinpoint what's going wrong.

**Comment by ZeldaLover227** [comment]
There is no crash screen it just goes straight back to the homescreen if I use the .cia app or the homebrew menu. And then OoT 3D won't open fully; it stays on the 3ds loading screen https://youtu.be/4LFAm_-qThE  https://youtu.be/dHjtbvhBKj0

**Comment by cjohnson57** [comment]
Were you using open Gerudo's fortress?

**Comment by ZeldaLover227** [comment]
Yes

**Comment by cjohnson57** [comment]
Thanks for the report, this should be fixed in the next nightly.
