### ISSUE TITLE
Crashes in Nightly-93b0117672acc0775c164026f71e772c5089e1b8

### ISSUE THREAD

**Issue by Homer2504** [gamestabled/OoT3D_Randomizer#146]
The randomizer crashes when it generates the playthrough, I´m using the 3dsx version and enabled the new option for chest appearance to "match with the content"

All other old versions work fine, only with this version crashes

Here an image of the crash
![Nightly-93b0117672acc0775c164026f71e772c5089e1b8](https://user-images.githubusercontent.com/84254205/118381995-271fc180-b5b6-11eb-95c9-6162e823c9b0.jpg)

PS: Sorry for my bad english if something is bad

**Comment by cjohnson57** [comment]
Thank you for reporting! The issue has to do with hints being enabled, we're investigating why. P.S. your English is fine :)
