### ISSUE TITLE
Crashes in latest two nightlies (dcf90b and a05507)

### ISSUE THREAD

**Issue by TheIrishBub** [gamestabled/OoT3D_Randomizer#159]
So I tried both .cia and .3dsx versions of the previous two nightlies, and experienced crashes during the generation of a seed. Nightly dcf90b would kick me to either the home menu or homebrew menu (using the cia and 3dsx versions, respectively), while nightly a05507 would just restart the 3ds entirely. I even tried setting Gerudo Fortress to something other than Open and turning off hints, as noted in previous crashing issues.

I don't have much to offer in the way of error logs, but I can at least provide the cached settings and cosmetics generated just before the crash from nightly a05507 (looks like I have to upload them as .txt; I hope that's fine).

[CACHED_SETTINGS.txt](https://github.com/gamestabled/OoT3D_Randomizer/files/6528332/CACHED_SETTINGS.txt)

[CACHED_COSMETICS.txt](https://github.com/gamestabled/OoT3D_Randomizer/files/6528334/CACHED_COSMETICS.txt)

**Comment by ianzerotwo** [comment]
same

**Comment by RevanXVIV** [comment]
Yeah I'm having this problem too.

**Comment by cjohnson57** [comment]
Nightly crashes are fixed now with recent changes

**Comment by piratejony** [comment]
I also am having this problem with citra, it just crashes when i try to launch OOT with the files in the mod folder
