### ISSUE TITLE
NTR cfw question/problem

### ISSUE THREAD

**Issue by PepGames** [gamestabled/OoT3D_Randomizer#187]
Does anyone know why this doesn't work with NTR cfw? Can NTR not run patched games? or is it something in the randomizers code that it is no longer considered a 3ds game? Wanted to stream this but now I cant. :(

**Comment by gymnast86** [comment]
OoT3D automatically turns off the 3DS internet connection when it boots up. This is a base game behavior and has nothing to do with the randomizer. You should be able to get around this by enabling the debugger in the rosalina menu before starting the game though.

**Comment by PepGames** [comment]
GOD BLESS YOU THIS WORKED
