### ISSUE TITLE
Failed To Install QR Code

### ISSUE THREAD

**Issue by 03bgood** [gamestabled/OoT3D_Randomizer#208]
It won't let me install the CIA file, I keep getting this error, whenever I scan the CIA QR code.

"Failed to Install from URL.
https://github.com/gamestabled/OoT3...
Result code: 0xD8A0A03C
Level: Permanent (27)
Summary: Invalid State (5)
Module: HTTP (40)
Desc: Failed to verify TLS certificate (60)"

**Comment by gymnast86** [comment]
Updating `FBI` to the latest version should fix this. https://github.com/Steveice10/FBI/releases/tag/2.6.1

**Comment by 03bgood** [comment]
I have ver. 2.4.12. I guess that one is outdated.
