### ISSUE TITLE
Crashes when entering Octorock miniboss room with Ruto

### ISSUE THREAD

**Issue by 03bgood** [gamestabled/OoT3D_Randomizer#210]
When I carry Princess Ruto to the room (Jabu Jabu's Belly) with the octorock miniboss, the game crashes and returns me to the 3DS menu telling me an error has occurred, this has happened twice. What do I do? This even happens if I enter the room without her.

**Comment by gamestabled** [comment]
This is a bug that is being looked into right now, it seems a mistake was made with overriding the model which is usually the zora's sapphire in that room to the randomized item model. For this playthrough, you may want to consider searching on youtube for tricks/glitches to skip that miniboss fight. One way or another this bug wont be present by the time of the next stable release.

**Comment by 03bgood** [comment]
The only way to fix this is to disable game patching via Luma and then play the vanilla game, it no longer crashes then.

Just beat Barinade and the randomized item in my playthrough was the Shadow Medallion. So that's the item that replaced the Zora's Sapphire and kept crashing the rando.

**Comment by gamestabled** [comment]
fixed by this commit https://github.com/gamestabled/OoT3D_Randomizer/commit/991258e50c1bfbe008f1c96b3f57a1ecd291085f

issue should no longer exist in future nightlies or releases

thanks for posting and sorry for the inconvenience on that playthrough 👍
