### ISSUE TITLE
Scrubsanity broken in latest update (Random Prices)

### ISSUE THREAD

**Issue by 03bgood** [gamestabled/OoT3D_Randomizer#219]
Some of the Deku Scrubs only say "What's that" after you defeat them preventing me from buying the randomized item from them. After that you cannot talk to them, anymore. Even when you exit the area and then do the same thing over again, the glitch still happens again. So far this has happened to me twice; in Ganon's Castle (far right scrub) and in the secret grotto in Lost Woods, right before the Sacred Forest Meadow (left scrub). Also minor text issue when talking to the scrubs; "Ok" in the dialog box is replaced with "BOK". This minor text issue was also present in the previous nightly build as well.

So far, this has only prevented me from getting minor items like Deku Sticks, but I wouldn't be surprised if any major items are locked out, because of this gamebreaking glitch.

**Comment by gamestabled** [comment]
do you know the commit hash of the version you are playing on?

**Comment by cjohnson57** [comment]
I just tried the scrubs in lost woods and they worked fine for me

**Comment by cjohnson57** [comment]
Ones in GC worked normally too

**Comment by 03bgood** [comment]
Just updated to v2.0 from a nightly build and had to delete my file and start a new seed. Hopefully this glitch has been fixed. They just released v2.0 an hour ago and before that, it was only nightly builds.

**Comment by cjohnson57** [comment]
I checked ~20 more scrub locations and the issue never happened- Not saying the issue doesn't exist but if it does it's rare and random which is an unfortunate combination

**Comment by 03bgood** [comment]
It just happened, again. I'm on v2.0 and it happened in Ganon's Castle again, this time it happened with the scrub to left, from the one it happened to in the last update. Please fix this, Gamestabled!

What happens if when you hit multiple scrubs, one of them says "What's that", which is the text Navi says in Lake Hylia when the bottle with Ruto's Letter is underwater or when Zelda throws the Ocarina of Time into the Hyrule Field moat. The text in the 3DS version actually says "Is there something unusual here?", the "What's that!?" is from the original N64 version. I have "random prices" turned on for Scrubnaity", this never occurred with "affordable prices" so it's defiantly a bug when you have "Random prices" selected. This is locking me out from getting some items, thus this is a gamebreaking bug within the rando itself.

**Comment by 03bgood** [comment]
![Uploading 20210616_020923.jpg…]()

**Comment by acedaemon** [comment]
I’ve seen this as well, I think it has to do with the price being set to 0

**Comment by cjohnson57** [comment]
I had a suspicion it might have something to do with random prices. The 0 rupee explanation would make sense. I guess for the time being, don't play with random prices for safety

**Comment by octobepis** [comment]
just had this issue and was locked out of getting the ocarina :')

**Comment by gamestabled** [comment]
This is fixed as of the most recent nightly. For players on 2.0, the bug can be avoided by not using the Random Prices setting for business scrubs.
