### ISSUE TITLE
Shadow Temple MQ Key Logic

### ISSUE THREAD

**Issue by swinginman** [gamestabled/OoT3D_Randomizer#260]
I was started a randomizer last weekend, and hit a dead end when trying to complete Shadow Temple. I enable random Master Quest dungeons for fun, as I haven't actually played through them all. That being said, I'm pretty sure the key logic got screwed up.
I had the setting that gives the player a map and compass at the beginning of temple enabled, so I was able to see all the chests I had access to. I opened every chest including the invisible one down by the ferry, not a single one had a small key. I don't think I am missing anything here, but if I am sorry in advanced. I attached my spoiler log, I believe this shows the problem as the first small key is in a room that requires a key to access. Look for the "Shadow Temple MQ" section.

[1970704417 (Gold Scale, Map, Lens of Truth, Lens of Truth, Fairy Ocarina)-spoilerlog.txt](https://github.com/gamestabled/OoT3D_Randomizer/files/6785523/1970704417.Gold.Scale.Map.Lens.of.Truth.Lens.of.Truth.Fairy.Ocarina.-spoilerlog.txt)

**Comment by gymnast86** [comment]
Your spoiler log indicates that you generated a No Logic playthrough. When No Logic is selected all the logical access rules get replaced with `true`, so there's a good possibility that you can end up getting key-locked in a dungeon when also setting Small Keys to Own Dungeon.

**Comment by swinginman** [comment]
Wow I can't believe I didn't see that lol. I was so certain I was using a logic seed that I didn't even think this was a possibility.

Thanks for the quick reply! Sorry about that, this is a non-issue!
