### ISSUE TITLE
Lost woods music issues with overworld entrances randomizer

### ISSUE THREAD

**Issue by UraYukimitsu** [gamestabled/OoT3D_Randomizer#277]
Using the v2.0-4e7748 nightly version:
- On the entrances that normally lead to the LW bridge (KF->bridge or HF->bridge), the music is set to nature noises regardless of what the music of the destination map is.
- On the GC->LW entrance, the LW music plays on the destination map on top of the normal music until the normal music changes eg. because of the day/night cycle

**Comment by gamestabled** [comment]
PR #323 fixed the bridge entrances for this, but not GC->LW
