### ISSUE TITLE
Zelda's Letter Can Be Deleted

### ISSUE THREAD

**Issue by minekraftminer** [gamestabled/OoT3D_Randomizer#285]
To put it short, If you get The Weird Egg after getting Zelda's Letter, Then the Weird Egg will replace Zelda's Letter making it impossible to do side quests like opening death mountain trail or starting the happy mask side quest.

**Comment by CharadeNut** [comment]
How did you reach Zelda's Letter, which is always carried by Zelda, without awakening Talon with the Weird Egg?
The reason why only Weird Egg is randomised is specifically to avoid this occurring.

**Comment by cjohnson57** [comment]
Yeah, glitching to get Zelda's Letter before egg is just something you have to not do if you don't want that risk.
