### ISSUE TITLE
Issues with Hot-Rodder Goron and Goron Link in the Latest Nightly

### ISSUE THREAD

**Issue by iadlast** [gamestabled/OoT3D_Randomizer#324]
Greetings,

I just wanted to report I'm unable to obtain the item from Hot-Rodder Goron as child Link, and the item and subsequent opening of the doors for Darunia's room and the Goron City shop from Goron Link because they just display the textbox from Biggoron instead of their proper dialog when stopped by a bomb, and then they just return to rolling without doing anything else.

The seed hash for my current run is as follows:

-Bottled Milk
-Skull Token
-Bombchu
-Beans
-Slingshot

EDIT: Just reached the Fire Temple. The rescued Gorons also have the same textbox as the two Gorons in the initial post, but they do play their rescue scenes normally.

**Comment by gamestabled** [comment]
Sounds like I made a mistake where the biggoron patches for shuffled adult trade ended up affecting other gorons as well. Thanks for reporting, it'll get looked into

**Comment by gamestabled** [comment]
this was fixed by commit [this commit](https://github.com/gamestabled/OoT3D_Randomizer/commit/797684a15bd2e16d662d7559ad0fd5116aecd58e)
