### ISSUE TITLE
[Cosmetics] Azure Blue and Vivid Cyan are the same color

### ISSUE THREAD

**Issue by iadlast** [gamestabled/OoT3D_Randomizer#335]
As the issue title says, both have the same exact RGB values in the code. I suspect it was a copypaste error of some sort.
Admittedly it's pretty minor, but I thought I'd mention it just in case.

**Comment by CharadeNut** [comment]
Azure Blue is 13**9E**D8. Vivid Cyan is 13**E9**D8.
https://i.imgur.com/5JfIdxh.png

**Comment by iadlast** [comment]
My bad, I was the one misreading the color codes. Still, I see a pull request was opened about the colors not rendering properly in the 3DS when compared to the ones from the N64 Randomizer.

**Comment by gamestabled** [comment]
pull #337 fixed/changed the custom colors list
