### ISSUE TITLE
No sound Background

### ISSUE THREAD

**Issue by CosmicOlw** [gamestabled/OoT3D_Randomizer#355]
I don't know if the option of “no background sound" could be implemented ,It seems to me an option that more than one might like.

**Comment by CharadeNut** [comment]
This tab is for issues encountered. Please refrain from using it for requests.

**Comment by gamestabled** [comment]
I think it's actually fine for well written/thought out requests (and it's not even the only one on here), and I think a disabled BGM option is actually a really good idea.
