### ISSUE TITLE
Dungeon-less run fails to generate

### ISSUE THREAD

**Issue by wiznillyp** [gamestabled/OoT3D_Randomizer#362]
Build: Stable release v2.0 & latest nighly (Nightly-a745c1)
Target: Citra

Attempting to create a dungeon-less run by randomizing overworld items but excluding all dungeon locations fails to generate.

Here are some relevant settings:
- Rainbow Bridge - 9 Dungeon Rewards
- Link's Pocket - Anything
- Songs - Anywhere
- Tokensanity - Overworld
- Everything else shuffled
- **Compass, map, small and boss key - own dungeon**
- Ganon Key - overworld
- GF key - Vanilla
- Exclude Item Locations - All overworld locations included
- Exclude Item Locations - All dungeon locations excluded
- No starting inventory
- Balanced Item Pool
- All locations reachable - off

Interestingly, with all settings the same, but keysanity fully enabled (small and boss keys set to anywhere) the randomizer succeeds.

I have attached a settings file for the failure case.  Just change small and boss keys from "own dungeon" to "anywhere" and it will work.
[BrokeSep18Nightly.zip](https://github.com/gamestabled/OoT3D_Randomizer/files/7203624/BrokeSep18Nightly.zip)

EDIT:  I omitted a precious detail pointed out by @cjohnson57. Even if you include enough locations for the keys this still fails (though, I imagine that after many attempts the keys may just fall into the correct locations and succeed).  Perhaps a priority on key placement is needed?

**Comment by cjohnson57** [comment]
You can't set keys to own dungeon and exclude all dungeon locations. Keys can't be placed in excluded locations. Which is why it works with keysanity. Nothing broken here, the randomizer is working as intended.

**Comment by wiznillyp** [comment]
@cjohnson57 Thanks for your response.

While I see and agree with your point, even if you include more than enough locations to cover all of the small and boss keys in each dungeon, it still fails. It may need to prioritize the placing of keys in this situation.

**Comment by cjohnson57** [comment]
I don't really foresee us changing the fill function to accommodate this situation. Why not just start with keys?

**Comment by wiznillyp** [comment]
> 
> 
> I don't really foresee us changing the fill function to accommodate this situation. Why not just start with keys?

That is a good workaround. But, that does not work if, for example, you wanted to remove only specific dungeons (like everyone's favorite Water Temple)

Bigger than this feature, I believed that it may be a limitation of the fill function in that a solution exists but can not be found without a bit of luck in the placement.  Maybe it is just the mathematician in me.  :D

**Comment by Thunderbird91** [comment]
> Compass, map, small and boss key - own dungeon

Wouldn't setting this to vanilla accomplish what you're looking for, or am I barking up the wrong tree? If you do this, the map, compass, and key locations don't show up in the Exclude Location list.
