### ISSUE TITLE
Logic doesn't allow Pierre usage to get to fire arrow location

### ISSUE THREAD

**Issue by KPJoshi** [gamestabled/OoT3D_Randomizer#374]
Issue is here:

https://github.com/gamestabled/OoT3D_Randomizer/blob/751a0be2bbaccb8eba820c8d6a38a21d6becc9f1/source/location_access.cpp#L631

`WaterTempleClear` should be replaced by `(WaterTempleClear || CanUse(DISTANT_SCARECROW))` to be consistent with OoT Randomizer:

https://github.com/TestRunnerSRL/OoT-Randomizer/blob/b7cac173e17373fc56701f22663df089c4dc808f/data/World/Overworld.json#L369

**Comment by cjohnson57** [comment]
While you can get to the platform with Pierre, we did not patch out the vanilla behavior that WT needs to be completed for the item to spawn.

**Comment by KPJoshi** [comment]
I'm not sure that is the case? The OoT 64 Randomizer seems to allow it (see link above). Or do you mean to say that OoT 64 Randomizer has to patch the game to allow it and you have not done so?

**Comment by Roberto-Nessy** [comment]
The logic is consistent with the ingame behaviour which is the important part, it's just that the ingame behaviour is different between 64 and 3d so the logic is as well

**Comment by KPJoshi** [comment]
I see. Thanks for the explanation. Maybe a comment next to this line for future readers mentioning this base game change would be useful then.

**Comment by cjohnson57** [comment]
Yeah, it's a weird/subtle difference but I believe gamestabled wanted to keep it to preserve some of the unique identity of 3D
