### ISSUE TITLE
Warping to the Sacred Forest Meadow as Adult gives a item 

### ISSUE THREAD

**Issue by Dkdavidlp** [gamestabled/OoT3D_Randomizer#398]
As described in the Title warping to Sacred Forest Meadow as Adult gives an Item without me having turned on song sanity or anything like it witch i dont think is supposed to happen.

**Comment by Efadd** [comment]
That's the vanilla Minuette of Forest check. The randomizer removes the cutscene where you meet Impa, so it's weird the first time, coming from vanilla.

**Comment by Dkdavidlp** [comment]
But in normal oot randomizer (so n64 version) it would give a song that's why reported this as an error

**Comment by cjohnson57** [comment]
Upload your spoiler

**Comment by Dkdavidlp** [comment]
I'll be sure to do that where is it located on my 3ds sd?

**Comment by gymnast86** [comment]
The spoiler log will be located in the `3ds` folder on your SD card. It'll have the seed and hash icons in the file name and will end in `spoilerlog.xml`

**Comment by Dkdavidlp** [comment]
[mbchu,_Boomerang_-spoilerlog_-_Kopie.pdf](https://github.com/gamestabled/OoT3D_Randomizer/files/7449754/mbchu._Boomerang_-spoilerlog_-_Kopie.pdf)

**Comment by Dkdavidlp** [comment]
uploaded my spoiler log and made a copy because i didnt wont convert the original

**Comment by cjohnson57** [comment]
Can't say I've ever seen a spoiler log as a pdf before, not sure how that happened lol.

But anyway, you shuffled songs to dungeon rewards, not song locations.

**Comment by Dkdavidlp** [comment]
ups ok since this was error occured on cause of my incompetence i will close this issue i guess
