### ISSUE TITLE
Spoiler log - If dungeon status (vanilla/MQ) is unknown, dungeon sections should be hidden in the spoiler log.

### ISSUE THREAD

**Issue by Thunderbird91** [gamestabled/OoT3D_Randomizer#414]
Currently, if a run is generated to not show the dungeon status on the dungeon summary screen, it is still possible to see whether the dungeon is vanilla or Master Quest by scrolling through the spoiler log. If one is looking through the locations to consider what areas to check next, scrolling past the dungeon sections is generally unavoidable.

I assume that if the spoiler log is set to fully show stuff, this is a non-issue. But when it's set to only show the full data for items that have been collected, then this situation applies.

**Comment by cjohnson57** [comment]
Implemented in #416
