### ISSUE TITLE
Wrong map in dungeon

### ISSUE THREAD

**Issue by Midnoclose** [gamestabled/OoT3D_Randomizer#417]
On the latest nightly version I stumbled upon a bug in which my map is wrong in the great deku tree. I am in the non master quest version of the dungeon and have collected every chest in the dungeon, however my map shows a chest that does not exist. I am not sure if the chest is in the master quest version of the dungeon because I am not all too familiar with master quest.

![Screenshot-11-11-2021-19-20](https://user-images.githubusercontent.com/24860483/141403422-9ba44f87-b360-47eb-8546-b7b709f6a7f1.png)
![Screenshot-11-11-2021-19-18](https://user-images.githubusercontent.com/24860483/141403447-3a4f606c-eb5a-4a83-966e-1738f7055f2b.png)
![Screenshot-11-11-2021-19-21-1](https://user-images.githubusercontent.com/24860483/141403565-a9c90a6c-01d7-4e17-9762-5f128057fccb.png)
![Screenshot-11-11-2021-19-21](https://user-images.githubusercontent.com/24860483/141403595-3e009eac-5d19-4ec2-b347-23c885718644.png)

**Comment by cjohnson57** [comment]
This will be fixed in #418, coincidentally posted 1 minute after this issue

**Comment by Midnoclose** [comment]
That's great to hear.
