### ISSUE TITLE
Unbeatable?

### ISSUE THREAD

**Issue by Seybs** [gamestabled/OoT3D_Randomizer#465]
So i did my first randomizer for oot3d. It was going well so far but i feel like im locked out of everything else because i dont have sarias song and zeldas lullaby. Is this possible if i do something wrong. Im so close to finishing. I can't access the water temple either because it's locked behind the shadow temple and haven't even gotten dins yet. Seems like i can't get any other items and it's supposed to be glitchless.

**Comment by cjohnson57** [comment]
Upload your spoiler; these shouldn't be posted as issues unless you upload your spoiler in #playthrough-help on the discord and it's a confirmed bug.
