### ISSUE TITLE
Gerudo Fortress Key

### ISSUE THREAD

**Issue by FerdigVibes** [gamestabled/OoT3D_Randomizer#479]
Hello! I've been enjoying my first OoT3D Randomizer. I've ran into a hiccup.

When I defeated the Gerudo Guard, they dropped a heart piece instead of the key to unlock the carpenter...

Is the Gerudo Fortress technically a "dungeon?" Or is the key considered a regular item I probably need to hunt down from a scrub?

I have keys randomized for their dungeon only, songs shuffled with songs, etc.

**Comment by enchanted-sword** [comment]
Gerudo Fortress keys are their own category and have their own shuffle setting. Depending on what settings you chose, they will either be shuffled to overworld locations, dungeon locations, or anywhere. However, in the future, I would advise asking such questions in the randomizer discord server as opposed to opening an issue on GitHub.

**Comment by FerdigVibes** [comment]
Thanks, Enchanted-Sword. Just felt off to me!
