### ISSUE TITLE
I picked up an entire chest

### ISSUE THREAD

**Issue by CowboyJoseph64** [gamestabled/OoT3D_Randomizer#480]
![image](https://user-images.githubusercontent.com/25892341/156489175-fb7335dd-48fb-4319-bd97-7d769511c8ae.png)

This is a trap chest, though I don't know which type besides it not being ice. All I know is that link was kicking the chest open instead of opening it normally, so I was instinctively mashing buttons to get out of ice (even though the way it was set it obviously wasn't always ice) and he seriously picked the entire thing up. I wish I even remotely understood how I did this. I'm on version 3.0

**Comment by cjohnson57** [comment]
.... huh

**Comment by cjohnson57** [comment]
Can you upload your spoiler?

**Comment by CowboyJoseph64** [comment]
I'm sorry, but what directory is the generated spoiler log?

**Comment by cjohnson57** [comment]
> If you want to view the spoiler log on your computer, it’s generated within the /3ds folder of your SD card. This spoiler log will tell you the location of every item in the game, as well as one way to logically collect all the items necessary to beat the seed (this is known as the “playthrough”). The spoiler log’s filename will be the combination of your seed and hash put together. An example of a spoiler log filename is 1002470105 (Frog, Gold Scale, Big Magic, Gold Scale, Bombchu)-spoilerlog.xml.

**Comment by CowboyJoseph64** [comment]
[1610922399 (Master Sword, Kokiri Tunic, Boss Key, Mask of Truth, Mushroom)-spoilerlog.zip](https://github.com/gamestabled/OoT3D_Randomizer/files/8175516/1610922399.Master.Sword.Kokiri.Tunic.Boss.Key.Mask.of.Truth.Mushroom.-spoilerlog.zip)
