### ISSUE TITLE
Hard crash when buying from various scrubs

### ISSUE THREAD

**Issue by amphyvi** [gamestabled/OoT3D_Randomizer#49]
Hi!  When I try buying from some Deku scrub salespeople, my 3DS hard crashes.

Some scrubs work, while others don't.  Not sure what the common theme is, if any.  So far, **this has happened at the following scrubs**:
- First scrub on the right, in the clearing with the 'SRM grotto' (in the Lost Woods, with the grotto that leads to the mask theater).  Tried this as child, couldn't try this as adult yet since I don't have Saria's Song.
- Scrub in the left corner, in the lower room to the right of the Bomb Bag chest in DC (the room with 2 scrubs).  Tried this as adult, couldn't try DC as child without bomb bag or goron bracelet (bracelet was in DC lol).

**Hash**:
- Hover Boots
- Frog
- SOLD OUT
- Shard of Agony
- Boss Key

**Error produced by Luma** (photo):
![20210320_150320](https://user-images.githubusercontent.com/51802000/111884391-728b6a00-898f-11eb-893e-48eab1c12e6b.jpg)

**Luma crash dumps**:
- LW scrub (I think):
https://cdn.discordapp.com/attachments/384187955327270942/822925108858847262/crash_dump_00000001.dmp
- DC scrub:
https://cdn.discordapp.com/attachments/384187955327270942/822925108577828884/crash_dump_00000002.dmp

Here is my **OOT3DR settings preset** (from /3ds/presets/oot3d):
https://cdn.discordapp.com/attachments/384187955327270942/822925733079941130/speedy_ez.bin

OOT3DR settings are being accessed via HBL.
OOT3D was installed via a .cia backup of the original cart I have.

N3DSXL US firmware: 11.14.0-46U
Luma3DS version: v10.2.1
I only just set up this N3DSXL a couple days ago for the first time, and everything has since been updated via Universal Updater.

Lastly, **here's everything I linked above, but in a ZIP** (since GitHub doesn't support .bin or .dmp files): 
[OOT3DR 20-03-2021.zip](https://github.com/gamestabled/OoT3D_Randomizer/files/6176357/OOT3DR.20-03-2021.zip)

Everything else seems to work just fine.  If I can do/provide anything else to help out, please let me know, thanks!

**Comment by gamestabled** [comment]
Thanks so much for reporting this and the detailed report that you left! This bug has been figured out, and the fix has been committed to the repo. 

The error only happens when you play with scrubsanity turned off, so you can avoid it for now by either using a different option for scrubsanity, or building the repo as it is now. Of course, it will also be included in an upcoming release alongside various other fixes. Thanks again!
