### ISSUE TITLE
Its not exactly an issue about the rando itself.

### ISSUE THREAD

**Issue by LinkexaYT** [gamestabled/OoT3D_Randomizer#491]
Its not exactly an issue about the rando itself, its moreso the discord support server. I was banned from the Discord server for asking for an apology from a Dev for how they've been treating me, I listed all what they think is bad behaviour of what I've done, and I was even accused of being rude by saying "Kewlan u should add a OOT3D Rando launcher so we can just boot it up from there (The rando generator can be set up there too), it creates less time to actually get into it" I want to be unbanned, and if I do get unbanned, I want them to apologise to me. My discord is Linkexa#0274, thank you.

![Screenshot_20220417-073441](https://user-images.githubusercontent.com/73471858/163704154-69a11532-99d2-41cf-aba8-72ae6b3d39a2.png)
![Screenshot_20220417-074437](https://user-images.githubusercontent.com/73471858/163704153-20ff8f63-61b1-43c6-bd69-6bc2abc99648.png)

**Comment by gamestabled** [comment]
This really isn't the place for this, and I'm going to close this issue.

That being said, I agree with the mod team's decision. Please do not interact with the repository again in this manner, and do not harass any of the staff, contributors, or other members of the discord or repo. If you do any of those things I will block you from the repository as well.
