### ISSUE TITLE
unable to randomize locations

### ISSUE THREAD

**Issue by angermanaged** [gamestabled/OoT3D_Randomizer#50]
im not sure if i got a glitch or it just isnt a feature but i cant seem to be able to randomize locations...

**Comment by cjohnson57** [comment]
What do you mean randomize locations? If you mean item locations, those are randomized. If you mean entrances, that is not yet a feature.

**Comment by angermanaged** [comment]
yeah i meant the entrances.. dang, thats like the best part too..
