### ISSUE TITLE
Freeze after creating scarecrow song.

### ISSUE THREAD

**Issue by jakxl27** [gamestabled/OoT3D_Randomizer#514]
After scarecrow dancing cutscene and conversation game freezes with link staring at scarecrow.

**Comment by HylianFreddy** [comment]
This is a base game bug that happens if you talk to the scarecrow Pierre and mash through the text too fast after he stops dancing.

Also note that talking to Pierre is useless. To get the scarecrow's song you only have to talk to the other scarecrow, Bonooru.
