### ISSUE TITLE
Glitchless Logic Error

### ISSUE THREAD

**Issue by DanaTheElf** [gamestabled/OoT3D_Randomizer#525]
Using "glitchless" settings, encountered an issue where Zelda's Lullaby was placed in the Death Mountain Crater, only reachable with the bean platform, while the Bolero of Fire was found in Ganon's Castle, and multiple Medallions required to gain entry to the Castle could only be accessed from chests gated behind Zelda's Lullaby, making it impossible to complete without glitches.
I was luckily able to use the Megaflip glitch to get Child Link to the bottom of the Crater and complete the game with no other issues, but obviously this is a problem for glitchless logic.

I suspect the issue arose because Child Link can enter the upper portion of the Crater, thus the location was flagged as "accessible" despite being unable to ordinarily reach the bean planting location without the warp song.

**Comment by HylianFreddy** [comment]
Could you please attach the spoiler log?

**Comment by DanaTheElf** [comment]
I'm unsure where to find that; would be happy to if you could point me in the right direction, but I've attached the patch file in case that helps.
[code.zip](https://github.com/gamestabled/OoT3D_Randomizer/files/9042380/code.zip)

**Comment by HylianFreddy** [comment]
The spoiler log is placed in the `3ds` folder on the SD card (if you're on Citra, click `File->Open Citra Folder` then navigate to `sdmc/3ds`).
The spoiler log’s filename will be the combination of your seed and hash put together. An example of a spoiler log filename is `1002470105 (Frog, Gold Scale, Big Magic, Gold Scale, Bombchu)-spoilerlog.xml`.

**Comment by DanaTheElf** [comment]
Aha, cheers! Here's the log:
[112478452 (Deku Stick, Master Sword, Cucco, Mushroom, Gold Scale)-spoilerlog.zip](https://github.com/gamestabled/OoT3D_Randomizer/files/9045834/112478452.Deku.Stick.Master.Sword.Cucco.Mushroom.Gold.Scale.-spoilerlog.zip)
:

**Comment by HylianFreddy** [comment]
The rainbow bridge was set to `Vanilla`. In the base game the bridge appears when you have Shadow and Spirit Medallions and the Light Arrow. The other medallions weren't required to finish the seed, and neither was Zelda's Lullaby.

For future reference, before opening an issue here I would suggest to report the problem you're having in the Discord server for OoT3DR (https://discord.gg/wumv4wWWeB), you'll generally get quicker answers too ;)

**Comment by DanaTheElf** [comment]
Oh wow, I genuinely didn't know that! Apologies!
I never even tried to cross the bridge because I didn't have all the medallions.
