### ISSUE TITLE
Logic issue Shiek in Death Mountain Crater

### ISSUE THREAD

**Issue by sion95** [gamestabled/OoT3D_Randomizer#527]
I played a randomizer with glitchless logic and closed door of time. But the Zora's Sapphier was on Shiek in Crater which made it impossible to obtain since I can only get it as adult but I couldn't become adult without the sapphier.

**Comment by HylianFreddy** [comment]
With closed DoT, you only need to play Song of Time to open it, there are no other requirements.

If you want it to require the spiritual stones and ocarina of time, you have to set the option to "Intended"

**Comment by PhlexPlexico** [comment]
Since there has been no response in a little over two years, will go ahead and close this.
