### ISSUE TITLE
Duplicate items on Randomizer?

### ISSUE THREAD

**Issue by AlbertoMSB** [gamestabled/OoT3D_Randomizer#53]
Hi! I am playing a randomizer seed and found a weird behavior that I don't know if it's a glitch or intended:
Some unique items are getting duplicated inside the randomizer. I've received two "Fairy Slingshots" and two "Megaton hammers". On the menu, they are normal, with only a single one of each, but they dropped from two different locations.
In the case of the Slingshot, I've received the first on the KF Kokiri Sword Chest. Second one I received from the Dodongos Cavern Deku Scrub Side Room Near Dodongos. However, according to the spoiler, I should have bought a Deku Stick (the text in-game was correct, only the received item that was duplicated).
On the Megaton Hammer, the first one I received from the Deku Tree Slingshot Room Side Chest, second one I purchased from the Scrub on Dodongo's Cavern Lobby, which showed as a Deku Shield (on the spoiler it also showed as selling a Deku Shield).
I dunno if this is intended behavior, but I'll report seeing as I've never encountered something similar on the OG OoT randomizer.

**Hash:**

- Mirror Shield 
- Lens of Truth 
- SOLD OUT 
- Fairy Ocarina 
- Silver Gauntlets

**OOT3DR Settings:**

Logic: Glitchless

- 	Forest: Closed
- 	Door of Time: Closed
- 	Zora's Fountain: Normal
- 	Gerudo Fortress: Normal
- 	Rainbow Bridge: Vanilla
- 	Random Ganon's Trials: Off
- 	  Trial Count: 6
- 	Starting Age: Child
- 	Bombchus in Logic: Off
- 	Bombchu Drops: On
- 	Mirror World: Off
- 	Shuffle Songs: Anywhere
- 	Tokensanity: Off
- 	Scrub Shuffle: Off
- 	Shuffle Cows: Off
- 	Shuffle Kokiri Sword: On
- 	Shuffle Ocarinas: On
- 	Shuffle Weird Egg: On
- 	Shuffle Gerudo Token: Off
- 	Shuffle Magic Beans: Off
- 	Maps/Compasses: Own Dungeon
- 	Small Keys: Own Dungeon
- 	Gerudo Fortress Keys: Vanilla
- 	Boss Keys: Own Dungeon
- 	Ganon's Boss Key: Own Dungeon
- 	Skip Child Sealth: Skip
- 	Four Poes Cutscene: Don't Skip
- 	Temple of Time Intro: Don't Skip
- 	Big Poe Target Count: 10
- 	Cuccos to return: 7
- 	Damage Multiplier: Default
- 	Starting Time: Day
- 	Generate Spoiler Log: Yes
- 	Item Pool: Balanced
- 	Ice Traps: Normal
- 	Adult Deku Stick: Disable
- 	Adult Boomerang: Disable
- 	Child Hammer: Disable

OOT3DR settings are being accessed via HBL running on a cartridge copy of OoT3D on an OG 3DS on US firmware 11.13.0-45U.
Luma3DS version: 10.2.1
I'm attaching the spoiler log for reference.

[1723017031Mirror ShieldLens of TruthSOLD OUTFairy OcarinaSilver Gauntlets-spoilerlog.txt](https://github.com/gamestabled/OoT3D_Randomizer/files/6178535/1723017031Mirror.ShieldLens.of.TruthSOLD.OUTFairy.OcarinaSilver.Gauntlets-spoilerlog.txt)

**Edit:** Jabu Jabu's Deku Scrub causes console to crash as soon as spoken to. 
Error produced by Luma: 
![image](https://user-images.githubusercontent.com/81119862/111924400-2588c000-8a83-11eb-86c5-da0c751116af.png)

**Comment by gamestabled** [comment]
Thanks for reporting this, it is due to a bug with having Scrub Shuffle set to "off" in the 1.0 release. It has been fixed starting with the nightly release from today.

**Comment by AlbertoMSB** [comment]
Thanks!
