### ISSUE TITLE
Child Deadhand w/ Sticks Trick Incorrect Description

### ISSUE THREAD

**Issue by WicketTVCDj2** [gamestabled/OoT3D_Randomizer#531]
It takes 9 jump slashes or 18 sticks to kill Deadhand. Assuming you use a new stick every hit. If done properly only 3 are needed.

**Comment by HylianFreddy** [comment]
The description has probably been copied over from the OoT randomizer.
In OoT3D killing Dead Hand as child takes 10 stick slashes or jump-slashes (they do the same damage).

Also if you use the broken stick glitch and do the fight really perfectly you can finish using only 1 stick (but you need to have at least 2 for the glitch)
