### ISSUE TITLE
[Request] Option To Remove The Fishing Minigame From The Randomization Pool

### ISSUE THREAD

**Issue by DiabloThePoet** [gamestabled/OoT3D_Randomizer#533]
I hope I'm not just speaking for myself, but I think it'd be really great to be able to choose the fishing minigame to be opted out of the item pool so that you don't always have to go play it, especially if you don't want to. Catching the fish can sometimes just be a big chore and not fun, and you have to potentially do it TWICE, so it would be great to be able to just turn it off specifically so an important or needed item won't be put up as the prize there. I'd still like to possibly have to do the other minigames, I'd just like to be able to turn this one off so I don't always have to do it.

**Comment by Kewlan** [comment]
You can exclude any location from the pool in `Detailed Logic Settings` -> `Exclude Locations`. This will place junk there instead.

**Comment by DiabloThePoet** [comment]
> You can exclude any location from the pool in `Detailed Logic Settings` -> `Exclude Locations`. This will place junk there instead.

I know, but this would require me to turn off all of Lake Hylia. I'd like to still need to search the top of the Lab and whatever I get for shooting an arrow into the morning sun. I'd just like to be able to specifically turn off the fishing minigame itself, just like how you can opt to not have to race Ingo to get Epona, since that minigame can be annoying as well.

**Comment by DiabloThePoet** [comment]
Note: I just discovered that it doesn't matter what fish you catch, the fisherman will always give you the prize. So I suppose that fixes this issue. Individually selecting which minigames you want to be active would still be a cool feature, though.

**Comment by Kewlan** [comment]
> I know, but this would require me to turn off all of Lake Hylia. I'd like to still need to search the top of the Lab and whatever I get for shooting an arrow into the morning sun. I'd just like to be able to specifically turn off the fishing minigame itself, just like how you can opt to not have to race Ingo to get Epona, since that minigame can be annoying as well.

That is exactly what you can do. The entries in the `Exclude Locations` menu are submenus where you turn of each specific location.

**Comment by DiabloThePoet** [comment]
> > I know, but this would require me to turn off all of Lake Hylia. I'd like to still need to search the top of the Lab and whatever I get for shooting an arrow into the morning sun. I'd just like to be able to specifically turn off the fishing minigame itself, just like how you can opt to not have to race Ingo to get Epona, since that minigame can be annoying as well.
> 
> That is exactly what you can do. The entries in the `Exclude Locations` menu are submenus where you turn of each specific location.

Oh, I see. Thanks for pointing that out. I did not know that.
