### ISSUE TITLE
Farore's Wind No Longer works? 

### ISSUE THREAD

**Issue by OTFree** [gamestabled/OoT3D_Randomizer#54]
Seed: 1170450957
Hash: Big Magic Hover Boots Big Magic Shard of Agony Lens of Truth 

Obtained Magic (first progressive), can't cast Farore's Wind anywhere (in dungeon not grayed out, or using "Restricted Items Glitch"). There is an audio cue telling me the item can't be used.

Does Farore's Wind require double-magic in order to work, because it doesn't in Vanilla OOT3D, or is the item potentially bugged? Doesn't work as child or adult, just to be clear. Running OOT3D v1.0 (.cia via Citra)

**Comment by gamestabled** [comment]
Very interesting, this is the first we've heard of an issue like this. FW should be usable as long as you have magic. Thanks for reporting this

**Comment by Kendragon7** [comment]
I can attest to this as well. I tried using Farore's wind in forest temple, everything looked fine except it gave me the can't-use-that sound when i tried. This is also the case for Din's fire for some bizarre reason, it just can't be used. I dont have fire arrows, but i have ice arrows and those work perfectly fine. Here's my gear and item screen in case those will be helpful in figuring why it doesnt work. I also have a video showcasing it. Is it related to deku stick, boomerang, and hammer being enabled for use on the wrong age? 
![16164913611774455889932625812372](https://user-images.githubusercontent.com/60989948/112123640-aaa4cf80-8b7e-11eb-82e4-cfc404345e55.jpg)
![16164913733401737037000762554722](https://user-images.githubusercontent.com/60989948/112123672-b1334700-8b7e-11eb-9b91-dc0600c34f42.jpg)
https://youtube.com/shorts/Z7Wd5CQM-O4

**Comment by gamestabled** [comment]
There are multiple different things in the game's save context that represent whether you have magic and how much. My guess is that this issue is due to one of those things being mishandled in some circumstance, in a way that magic arrows don't mind, but fairy spells do.

**Comment by gamestabled** [comment]
Following up on this, the fix has been merged into the repo, so it'll be available in the next release (or in nightlies starting now)

**Comment by TheIrishBub** [comment]
I apologize for not mentioning this before, but I had the same issue with a seed I had a few days ago (before the fix). I had Ganon's boss key behind LACS-Medallions, and Shadow Temple had one of the medallions I needed. I couldn't actually enter Shadow because I couldn't light the torches with Din's Fire (despite having both Din's and magic), and I doubt using fire arrows is in glitchless logic, so that led to this seed being unbeatable, afaik.

Glad to see that this issue has been fixed!
