### ISSUE TITLE
Progressive Ocarina behind Dodongos Cavern GS Scarecrow and Armos Statue trick disabled 

### ISSUE THREAD

**Issue by SamuelM333** [gamestabled/OoT3D_Randomizer#555]
After a few hours of searching for the Ocarina I gave up and checked the spoiler log. To my surprise the WotH Ocarina was behind the Scarecrow song GS in DC, which isn't reachable in glitchless logic. I also have the Armos Statue trick disabled, but ended up having to do it anyway in order to progress. Am I missing something? Is this reachable with a different method? I had longshot but couldn't find an angle to hit it. Also, the other Ocarina was not reachable at this point.

[Spoiler log](https://pastebin.com/raw/iCd3nh0U)

Thank you for your great work. I'm having a blast on my 3DS!

**Comment by LinkexaYT** [comment]
if you have access to Spirit Temple, there's one there "Spirit Temple Child Climb East Chest"

**Comment by HylianFreddy** [comment]
Getting that skulltula with longshot is possible and considered in the base logic.
Here you can see where to stand to hit it: https://youtu.be/17cSvioIPd8?t=2h34m11s

**Comment by SamuelM333** [comment]
@LinkexaYT I did, but only as adult, and by not having the Ocarina I couldn't warp back as child (I didn't have requiem of spirit at this point either).

@HylianFreddy wow didn't know that, thank you! Guess will have to add another trick to my toolbox. This made me learn the Armos Statue trick as well, which is different than 64 OoT. This one even required frame buffering, so in the end it just made me a better player 😄 Now I feel confident enabling that trick for my next run.

I will see if I'm able to add this to https://wiki.ootrandomizer.com/index.php?title=Logic#Dodongo.27s_Cavern since this is what I'm using as a last resort before checking spoiler log, but didn't have this comment about longshot with an angle.
