### ISSUE TITLE
[Feature Request] Add textures for chests that contain a Skulltula Token

### ISSUE THREAD

**Issue by LinkexaYT** [gamestabled/OoT3D_Randomizer#564]
You know how we have an option to enable chests matching colour and size of the contents. We don't have textures for chests containing skulltula tokens, so I thought, maybe there should be, it allows players who enable that option to know if the chest is going to contain a token or not without using spoiler log.

**Comment by LinkexaYT** [comment]
Is this just not going to be noticed by gymnast86?

**Comment by PhlexPlexico** [comment]
Looks like as of commit https://github.com/gamestabled/OoT3D_Randomizer/commit/e6f62f15fc63809383fcd711498b035bcf31bfd1 this has been implemented.
