### ISSUE TITLE
[Name Bug] Mirror Shield is named "Mirror of Twilight"

### ISSUE THREAD

**Issue by LinkexaYT** [gamestabled/OoT3D_Randomizer#572]
On the spoiler log and in the shops, Mirror Shield is named "Mirror of Twilight", which confuses me because Mirror of Twilight is a complete different thing. When I checked spoiler log, I was like "Did they suddenly make it possible to go through Twilight Realm" and then suddenly, I find out it's a Mirror Shield. Maybe it's a typo on your end which may need to be fixed. Please solve this ASAP.
![16657571385197022487167626751596](https://user-images.githubusercontent.com/73471858/195869599-6c616822-44c1-442b-aab1-30db410036a5.jpg)
![16657571589104710995616244043912](https://user-images.githubusercontent.com/73471858/195869667-f8ba9cd6-d651-42ca-8bd0-1e4bb16591ee.jpg)

**Comment by PhlexPlexico** [comment]
Did you by chance end up purchasing it? :)

**Comment by LinkexaYT** [comment]
nope cuz  its pointless without ocarina

**Comment by PhlexPlexico** [comment]
Please purchase it then and report back! You can use the search functionality on GitHub to see that this is intended behaviour, and not a bug.

**Comment by zeldaking** [comment]
its a ice trap item.
