### ISSUE TITLE
Uncompletable Seed Generated with Water and Spirit Medallions in the Shadow Temple

### ISSUE THREAD

**Issue by iadlast** [gamestabled/OoT3D_Randomizer#594]
Hello.

I just wanted to say that I've been greatly enjoying the randomizer, especially now with the randomized Mirror World option for all screens, but in my most recent playthrough, I've hit a deadlock in one of the seeds I generated: basically, it needs all dungeon rewards and the Light Arrows for the Temple of Time Light Arrows cutscene and for the Ganon's Castle rainbow bridge, but the Water and Spirit Medallions seem (I have the spoiler log set to hidden, so I'm not entirely sure about it) to be in the Shadow Temple past the chasm that requires the Hover Boots, and I haven't been able to find the Boots anywhere in any of the other locations I've checked thus far. The only other locations that I still have remaining are the Carpet Seller in the Haunted Wasteland, and the first silver rupee chest in the vanilla Spirit Temple, both of which also require the Hover Boots to be reached to the best of my knowledge.

The seed hash for this seed is Boss Key, Silver Gauntlets, Mask of Truth, Megaton Hammer and Shard of Agony.

**Comment by Dunsay** [comment]
Even if you have set in game spoler log to hidden, you can access your spoiler log as an .xml file in the /3ds/ folder on your memory card.

**Comment by Roberto-Nessy** [comment]
Neither of those locations require hover boots. You can reach the carpet salesman using longshot to cross the quicksand and a midair jumpslash to reach the carpet. You can also get the floating silver rupee with a jumpslash (although it's a bit inconsistent)

**Comment by PhlexPlexico** [comment]
If you're still having issues, feel free to re-open this!
