### ISSUE TITLE
Reproducible Crash - First Deku Scrub 

### ISSUE THREAD

**Issue by QuantumCarrot** [gamestabled/OoT3D_Randomizer#68]
In the Lost Woods area with the entrance to the mask stage, attempting to buy the item from the Deku Scrub nearest the entrance causes a crash. No issues buying the item from the second Scrub. Attached is a photo of the crash screen. Please let me know what might be helpful in terms of logs or randomizer-generated files.

Thanks everyone for making this randomizer a reality!

![IMG_20210323_200332](https://user-images.githubusercontent.com/81233177/112138738-3832fe80-8c15-11eb-9d6d-cbe19cc34716.jpg)

**Comment by cjohnson57** [comment]
Thanks for the report, is this still on version 1.0? This should have been fixed in 1.0.1

**Comment by dberghoff** [comment]
I just experienced the same issue on version 1.0.1. I saved two crash dumps and they're slightly different, not sure if that's important.

[crash_dump_00000000.txt](https://github.com/gamestabled/OoT3D_Randomizer/files/6191539/crash_dump_00000000.txt)
[crash_dump_00000001.txt](https://github.com/gamestabled/OoT3D_Randomizer/files/6191540/crash_dump_00000001.txt)

**Comment by cjohnson57** [comment]
Was it with the same scrub mentioned in the OP, and was scrubsanity on or off?

**Comment by dberghoff** [comment]
It was, but I just double checked the randomizer and it says I'm using version 1.0, but I downloaded the cia from the latest release. Maybe the wrong file was uploaded?

**Comment by gamestabled** [comment]
did you actually install the new CIA?

**Comment by QuantumCarrot** [comment]
> 
> 
> Thanks for the report, is this still on version 1.0? This should have been fixed in 1.0.1

Yes, this was on 1.0, run from 3dsx, with scrub settings unchanged from the randomizer defaults. I'll update to the new version. Thanks!
[OoT 3DS Rando logs.zip](https://github.com/gamestabled/OoT3D_Randomizer/files/6193237/OoT.3DS.Rando.logs.zip)

**Comment by gamestabled** [comment]
Cool, I'm going to close this issue because the business scrub problem has been resolved. @Nemitis it sounds like you had a problem with the updater, if that is still a problem, go ahead and open a new issue for it.

Thanks all!
