### ISSUE TITLE
Hard lock, young link can't use Pocket cucco

### ISSUE THREAD

**Issue by Plep-m** [gamestabled/OoT3D_Randomizer#686]
in my seed the egg was in a shop so i bought it but i had previously in my inventory a biggoron quest item now the game think the pocket cucco is an adult item

**Comment by Linkdash2019** [comment]
There are 2 pocket cucco’s a child cucco and an adult cucco.

**Comment by PhlexPlexico** [comment]
Feel free to re-open if needed, but would you please either take a screenshot to confirm it's the child cucco or adult cucco.
