### ISSUE TITLE
No song from Malon

### ISSUE THREAD

**Issue by RZeratsky** [gamestabled/OoT3D_Randomizer#69]
Loving the Rando, thank you SO much for bringing this to OoT3D.

Encountered what I think is a bug. I got Epona's Song from Impa after visiting Zelda, then went to the ranch and Malon won't give me a song. Pulling out the ocarina after talking to her the normal amount of times does nothing and talking to her again she says basically "Epona likes you now," but I got nothing from the encounter.

Hash is Mushroom, Frog, Mushroom, Gold Scale, Bottled Milk if that helps.

**Comment by PowerBFG** [comment]
Can confirm had a similar issue but after talking to Malon and pulling out my ocarina multiple times it finally gave me the song.
I also received Epona's song from Impa after visiting Zelda.
Seed Hash: Saw, Cucco, Mushroom, Bow, Skull Token

I was able to complete my first rando run ever with this version thanks for all your hard work.

**Comment by gamestabled** [comment]
There's a known issue where certain locations (song locations, fairy fountains) can fail to give you an item if you swing your sword at exactly the wrong time. It has a tendency to happen if you pull out ocarina and immediately start mashing B. If this sounds like this is what happened to you, it's known and it's a high priority issue

**Comment by gamestabled** [comment]
This issue has now been fixed an committed to the repo. It'll be fixed in the next release, or in nightlies starting now
