### ISSUE TITLE
Still randomly crashes

### ISSUE THREAD

**Issue by 03bgood** [gamestabled/OoT3D_Randomizer#708]
This happens during loading zones and warping! It's been happening for a very long time, now and it has yet to be fixed.

**Comment by Kewlan** [comment]
Post your spoiler log and crash dump.

**Comment by 03bgood** [comment]
It crashes to the home menu. Please fix this shit, it's the worst! It's happened to me, twice in the current seed I'm playing and it always happens when either going through a loading zone or warping via the Ocarina! Why haven't the devs fixed this, yet? There's no excuse for this kind of laziness! It's been a known issue for like 2-3 years, now!

**Comment by Kewlan** [comment]
If you want it fixed you're gonna have to send your spoiler log and the crash dump so we can actually look into why it's crashing.

**Comment by PhlexPlexico** [comment]
Closing as duplicate of https://github.com/gamestabled/OoT3D_Randomizer/issues/529

As mentioned in previous issues, please enable Exception Handlers in Luma and provide the crash dump here. If this is not done **we will not be able assist you**. Please also include the spoiler log, which is located at `sdcard:/OoT3DR/Logs`.

Thanks.
