### ISSUE TITLE
Is it possible to use the Camera Mod AND the Randomizer ?

### ISSUE THREAD

**Issue by WildLONLON** [gamestabled/OoT3D_Randomizer#715]
I'm interested in Randomized Ocarina of Time 3D.
I've got the tool to generate code.ips, exheader.bin files and a romfs folder (all of which make up the Random seed) that I just need to move to the MOD location of an OoT USA.
So far, so good!

But I'm also used to using an MOD allowing the right Stick to be used to control the camera, which is also installed via files called code.ips and exheader.bin...

• I haven't had a chance to try it out, but is it possible to rename the .ips and .bin files without making them inactive?
Or...
• Is there a way of injecting data from the Camera MOD's .ips and .bin into the Randomization MOD's .ips and .bin? 

These may seem silly questions, but they're not really my area of expertise...

**Comment by Kewlan** [comment]
The latest Nightly has freecam built in, and it's on by default.

You can download it here: https://github.com/gamestabled/OoT3D_Randomizer/releases
