### ISSUE TITLE
[Feature Request] Randomized Starting Spawns for Child and Adult

### ISSUE THREAD

**Issue by Necrofitz** [gamestabled/OoT3D_Randomizer#716]
Request for a feature that allows child and adult spawns to be changed from their vanilla locations of Link's house for child and Temple of Time for adult. If possible to change these spawns, should only need a fairly small location blacklist to avoid soft locking either age on a save and reset and when starting the seed.

This would be appreciated, as randomized spawns open the door to increasingly interesting ways to route a seed, at times effectively becoming warp songs themselves.

**Comment by Kewlan** [comment]
This already exists. You can enable it in World Settings: 
![image](https://github.com/gamestabled/OoT3D_Randomizer/assets/5352197/8ee25011-321e-4c5a-a66c-040d3a919efc)
If you can't see the option, update to the latest Nightly build here: 
https://github.com/gamestabled/OoT3D_Randomizer/releases

**Comment by Necrofitz** [comment]
Ah, it was under shuffle entrances. Didn't even glance at that since I don't really consider this to be in the same category as entrance randomization. Updated suggestion may be grouping it under the Starting Age option. At least I know it's there though and will otherwise close this.
