### ISSUE TITLE
Randomizer just completely does not work 

### ISSUE THREAD

**Issue by Roratronic** [gamestabled/OoT3D_Randomizer#734]
When ever I use the randomizer and go to oot3d it does not say 'tloz oot randamizer' it just says the normal 'tloz oot' I don't know what I've done wrong. I have downloaded with the 3dsx qr code and and cia qrcode I have a video showing the problem  if anyone can try to help please do 

Any help will be greatly appreciated 

https://youtu.be/tzHykRmSzIg?si=Xyhw1vrXLivOb7Eb

**Comment by fabfabfabiiii** [comment]
You have to enable patching. (Power on + press select)

**Comment by Roratronic** [comment]
> You have to enable patching. (Power on + press select)
Thanks for the quick response but I have it enabled 
![20240514_193413](https://github.com/gamestabled/OoT3D_Randomizer/assets/169838683/ad4f659c-84d9-462e-a784-2668334a03bf)

**Comment by fabfabfabiiii** [comment]
> > You have to enable patching. (Power on + press select)
> Thanks for the quick response but I have it enabled 
> ![20240514_193413](https://github.com/gamestabled/OoT3D_Randomizer/assets/169838683/ad4f659c-84d9-462e-a784-2668334a03bf)
> 
> 
> 

Are you Sure that you have the Vorrecht Version of the game?

**Comment by Roratronic** [comment]
> > > You have to enable patching. (Power on + press select)
> > > Thanks for the quick response but I have it enabled
> > > ![20240514_193413](https://private-user-images.githubusercontent.com/169838683/330553538-ad4f659c-84d9-462e-a784-2668334a03bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTI2NTgsIm5iZiI6MTcxNTcxMjM1OCwicGF0aCI6Ii8xNjk4Mzg2ODMvMzMwNTUzNTM4LWFkNGY2NTljLTg0ZDktNDYyZS1hNzg0LTI2NjgzMzRhMDNiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxODQ1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWYyZTFhNjZjZDc4MzJiOTI4YTM4YTEzNmYwMzA1ZTNjNzg4Mjg0ZTMzMjY5MmY4ZGFhMDliZmI1MTAzMzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iIeJw1Y0mMgw9ZhVBapql4QSxZaVl0cgXFAcnJbM22Y)
> 
> Are you Sure that you have the Vorrecht Version of the game?

Do you know how to check if I had that version  I only the cartridge?

**Comment by Roratronic** [comment]
> > > You have to enable patching. (Power on + press select)
> > > Thanks for the quick response but I have it enabled
> > > ![20240514_193413](https://private-user-images.githubusercontent.com/169838683/330553538-ad4f659c-84d9-462e-a784-2668334a03bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTQ4NTksIm5iZiI6MTcxNTcxNDU1OSwicGF0aCI6Ii8xNjk4Mzg2ODMvMzMwNTUzNTM4LWFkNGY2NTljLTg0ZDktNDYyZS1hNzg0LTI2NjgzMzRhMDNiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxOTIyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2U3NmE2NjEwMmE1ZmJjYmM1N2IxMDFkZTBjYTQxYWU1NTZkMGZiMzQ2ZDk1ZTAyMjEzYmI4MGQzZjM0OTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNuAi9vI3kYk31lOsZKu8PchQrmcwAeoq0RubICrPnA)
> 
> Are you Sure that you have the Vorrecht Version of the game?

Do I need the Vorrecht version?

**Comment by fabfabfabiiii** [comment]
> > > > You have to enable patching. (Power on + press select)
> > > > Thanks for the quick response but I have it enabled
> > > > ![20240514_193413](https://private-user-images.githubusercontent.com/169838683/330553538-ad4f659c-84d9-462e-a784-2668334a03bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTQ4NTksIm5iZiI6MTcxNTcxNDU1OSwicGF0aCI6Ii8xNjk4Mzg2ODMvMzMwNTUzNTM4LWFkNGY2NTljLTg0ZDktNDYyZS1hNzg0LTI2NjgzMzRhMDNiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxOTIyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2U3NmE2NjEwMmE1ZmJjYmM1N2IxMDFkZTBjYTQxYWU1NTZkMGZiMzQ2ZDk1ZTAyMjEzYmI4MGQzZjM0OTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNuAi9vI3kYk31lOsZKu8PchQrmcwAeoq0RubICrPnA)
> > 
> > Are you Sure that you have the Vorrecht Version of the game?
> 
> Do I need the Vorrecht version?

Sry, german auto correction😭 i mean the correct version

**Comment by Roratronic** [comment]
> > > > > You have to enable patching. (Power on + press select)
> > > > > Thanks for the quick response but I have it enabled
> > > > > ![20240514_193413](https://private-user-images.githubusercontent.com/169838683/330553538-ad4f659c-84d9-462e-a784-2668334a03bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTQ4NTksIm5iZiI6MTcxNTcxNDU1OSwicGF0aCI6Ii8xNjk4Mzg2ODMvMzMwNTUzNTM4LWFkNGY2NTljLTg0ZDktNDYyZS1hNzg0LTI2NjgzMzRhMDNiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxOTIyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2U3NmE2NjEwMmE1ZmJjYmM1N2IxMDFkZTBjYTQxYWU1NTZkMGZiMzQ2ZDk1ZTAyMjEzYmI4MGQzZjM0OTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNuAi9vI3kYk31lOsZKu8PchQrmcwAeoq0RubICrPnA)
> > > 
> > > 
> > > Are you Sure that you have the Vorrecht Version of the game?
> > 
> > 
> > Do I need the Vorrecht version?
> 
> Sry, german auto correction😭 i mean the correct version

Oh I see 😂 which is the correct version?

**Comment by fabfabfabiiii** [comment]
> > > > > > You have to enable patching. (Power on + press select)
> > > > > > Thanks for the quick response but I have it enabled
> > > > > > ![20240514_193413](https://private-user-images.githubusercontent.com/169838683/330553538-ad4f659c-84d9-462e-a784-2668334a03bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTQ4NTksIm5iZiI6MTcxNTcxNDU1OSwicGF0aCI6Ii8xNjk4Mzg2ODMvMzMwNTUzNTM4LWFkNGY2NTljLTg0ZDktNDYyZS1hNzg0LTI2NjgzMzRhMDNiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxOTIyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2U3NmE2NjEwMmE1ZmJjYmM1N2IxMDFkZTBjYTQxYWU1NTZkMGZiMzQ2ZDk1ZTAyMjEzYmI4MGQzZjM0OTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNuAi9vI3kYk31lOsZKu8PchQrmcwAeoq0RubICrPnA)
> > > > 
> > > > 
> > > > Are you Sure that you have the Vorrecht Version of the game?
> > > 
> > > 
> > > Do I need the Vorrecht version?
> > 
> > Sry, german auto correction😭 i mean the correct version
> 
> Oh I see 😂 which is the correct version?

You have to use the USA version of the game. 
But have you already generated a seed or only started the game?

**Comment by Roratronic** [comment]
> > > > > > > You have to enable patching. (Power on + press select)
> > > > > > > Thanks for the quick response but I have it enabled
> > > > > > > ![20240514_193413](https://private-user-images.githubusercontent.com/169838683/330553538-ad4f659c-84d9-462e-a784-2668334a03bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTQ4NTksIm5iZiI6MTcxNTcxNDU1OSwicGF0aCI6Ii8xNjk4Mzg2ODMvMzMwNTUzNTM4LWFkNGY2NTljLTg0ZDktNDYyZS1hNzg0LTI2NjgzMzRhMDNiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxOTIyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2U3NmE2NjEwMmE1ZmJjYmM1N2IxMDFkZTBjYTQxYWU1NTZkMGZiMzQ2ZDk1ZTAyMjEzYmI4MGQzZjM0OTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNuAi9vI3kYk31lOsZKu8PchQrmcwAeoq0RubICrPnA)
> > > > > 
> > > > > 
> > > > > Are you Sure that you have the Vorrecht Version of the game?
> > > > 
> > > > 
> > > > Do I need the Vorrecht version?
> > > 
> > > 
> > > Sry, german auto correction😭 i mean the correct version
> > 
> > 
> > Oh I see 😂 which is the correct version?
> 
> You have to use the USA version of the game. But have you already generated a seed or only started the game?

Well I've generated the seed then started the game and made a new save then finished the intro but nothing happened I think I have the EU version but I'll download the USA version and see if anything changes

**Comment by Roratronic** [comment]
> > > > > > > > You have to enable patching. (Power on + press select)
> > > > > > > > Thanks for the quick response but I have it enabled
> > > > > > > > ![20240514_193413](https://private-user-images.githubusercontent.com/169838683/330553538-ad4f659c-84d9-462e-a784-2668334a03bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTQ4NTksIm5iZiI6MTcxNTcxNDU1OSwicGF0aCI6Ii8xNjk4Mzg2ODMvMzMwNTUzNTM4LWFkNGY2NTljLTg0ZDktNDYyZS1hNzg0LTI2NjgzMzRhMDNiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxOTIyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2U3NmE2NjEwMmE1ZmJjYmM1N2IxMDFkZTBjYTQxYWU1NTZkMGZiMzQ2ZDk1ZTAyMjEzYmI4MGQzZjM0OTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNuAi9vI3kYk31lOsZKu8PchQrmcwAeoq0RubICrPnA)
> > > > > > 
> > > > > > 
> > > > > > Are you Sure that you have the Vorrecht Version of the game?
> > > > > 
> > > > > 
> > > > > Do I need the Vorrecht version?
> > > > 
> > > > 
> > > > Sry, german auto correction😭 i mean the correct version
> > > 
> > > 
> > > Oh I see 😂 which is the correct version?
> > 
> > 
> > You have to use the USA version of the game. But have you already generated a seed or only started the game?
> 
> Well I've generated the seed then started the game and made a new save then finished the intro but nothing happened I think I have the EU version but I'll download the USA version and see if anything changes

It's going to take 1 and a half hours so i will tell you if it works in a while

**Comment by HylianFreddy** [comment]
You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using.
You can find the latest release here: https://github.com/gamestabled/OoT3D_Randomizer/releases

**Comment by Roratronic** [comment]
> You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here: 

> You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here: https://github.com/gamestabled/OoT3D_Randomizer/releases

Thank you so much 
I'll see if this works if it does I'll close this if it doesn't I'll try the USA version again

**Comment by Roratronic** [comment]
> > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here:
> 
> > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here: https://github.com/gamestabled/OoT3D_Randomizer/releases
> 
> Thank you so much I'll see if this works if it does I'll close this if it doesn't I'll try the USA version again

So I have tried downloading both versions but they won't show up do you know why this is?

**Comment by HylianFreddy** [comment]
> > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here:
> > 
> > 
> > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here: https://github.com/gamestabled/OoT3D_Randomizer/releases
> > 
> > 
> > Thank you so much I'll see if this works if it does I'll close this if it doesn't I'll try the USA version again
> 
> So I have tried downloading both versions but they won't show up do you know why this is?

What method are you using to install them? If you installed the CIA version with FBI then you can just open the Randomizer app from where you already had it, it won't add a new icon.

If you instead download the 3DSX version then you have to launch it through the Homebrew Launcher

**Comment by Roratronic** [comment]
> > > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here:
> > > 
> > > 
> > > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here: https://github.com/gamestabled/OoT3D_Randomizer/releases
> > > 
> > > 
> > > Thank you so much I'll see if this works if it does I'll close this if it doesn't I'll try the USA version again
> > 
> > 
> > So I have tried downloading both versions but they won't show up do you know why this is?
> 
> What method are you using to install them? If you installed the CIA version with FBI then you can just open the Randomizer app from where you already had it, it won't add a new icon.
> 
> If you instead download the 3DSX version then you have to launch it through the Homebrew Lau

> > > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here:
> > > 
> > > 
> > > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here: https://github.com/gamestabled/OoT3D_Randomizer/releases
> > > 
> > > 
> > > Thank you so much I'll see if this works if it does I'll close this if it doesn't I'll try the USA version again
> > 
> > 
> > So I have tried downloading both versions but they won't show up do you know why this is?
> 
> What method are you using to install them? If you installed the CIA version with FBI then you can just open the Randomizer app from where you already had it, it won't add a new icon.
> 
> If you instead download the 3DSX version then you have to launch it through the Homebrew Launcher

Oh I see thank you I used the fbi remote install qr code thank you I didn't realise thar it was not a new icon thank you

**Comment by Roratronic** [comment]
> > > > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here:
> > > > 
> > > > 
> > > > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here: https://github.com/gamestabled/OoT3D_Randomizer/releases
> > > > 
> > > > 
> > > > Thank you so much I'll see if this works if it does I'll close this if it doesn't I'll try the USA version again
> > > 
> > > 
> > > So I have tried downloading both versions but they won't show up do you know why this is?
> > 
> > 
> > What method are you using to install them? If you installed the CIA version with FBI then you can just open the Randomizer app from where you already had it, it won't add a new icon.
> > If you instead download the 3DSX version then you have to launch it through the Homebrew Lau
> 
> > > > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here:
> > > > 
> > > > 
> > > > > You can play on the European version if you use the Nightly version of the Randomizer, which also has a lot more features than the stable one you're using. You can find the latest release here: https://github.com/gamestabled/OoT3D_Randomizer/releases
> > > > 
> > > > 
> > > > Thank you so much I'll see if this works if it does I'll close this if it doesn't I'll try the USA version again
> > > 
> > > 
> > > So I have tried downloading both versions but they won't show up do you know why this is?
> > 
> > 
> > What method are you using to install them? If you installed the CIA version with FBI then you can just open the Randomizer app from where you already had it, it won't add a new icon.
> > If you instead download the 3DSX version then you have to launch it through the Homebrew Launcher
> 
> Oh I see thank you I used the fbi remote install qr code thank you I didn't realise thar it was not a new icon thank you

IT WORKED! Thank you so much for your help if it wasn't for you I would be stuck with this forever

**Comment by HylianFreddy** [comment]
I'm glad I could help. Have fun playing!
