### ISSUE TITLE
Console locks up sometimes when opening the randomizer menu

### ISSUE THREAD

**Issue by blasterboyorange** [gamestabled/OoT3D_Randomizer#739]
New Nintendo 2DS, Sys 11.17.0-50U
Luma 3DS v13.1.1
randomizer v3.1

Unsure what causes it, console just occasionally locks up when opening the randomizer menu. It won't respond to any inputs besides holding down the power button to force shutdown.

I'm honestly pretty tech illiterate and I'm afraid of somehow messing up my console in a way I can't fix by further testing this issue, so the only information I have is that it happened twice for seemingly no reason.

**Comment by Kewlan** [comment]
Can you try the latest Nightly and see if it still happens? It can be downloaded here: https://github.com/gamestabled/OoT3D_Randomizer/releases

**Comment by blasterboyorange** [comment]
Nevermind! It most likely wasn't even a lockup, it was my busted circle pad!

I've had this console for well over a decade and the circle pad drifts up unless I use a down input to correct it lol

the randomizer menu doesn't let you input with buttons while the circle pad is registered as holding a direction (even slightly) and the home and power buttons are just naturally disabled in the menu anyway, so there's no issue, I'm just a little bit stupid haha
