### ISSUE TITLE
[Question] how the custom musics/models works?

### ISSUE THREAD

**Issue by Licuatronix** [gamestabled/OoT3D_Randomizer#741]
custom_models files and the custom_music folder

I would like to know exactly how you can use these features, like whats the music format or the model format to make this work, the recomended tools, etc

**Comment by Kewlan** [comment]
For custom music, see here: https://github.com/Kewlan/OoT3D-Custom-Sequences

**Comment by Licuatronix** [comment]
> For custom music, see here: https://github.com/Kewlan/OoT3D-Custom-Sequences

Thanks, and what about the custom model? Or is a unfinished feature?

**Comment by Kewlan** [comment]
We don't have custom model support directly in the randomizer. You can instead replace models yourself using regular mods and placing the files in the appropriate folder.
If you're asking because of multiplayer, seeing other's own model is not supported.

**Comment by Licuatronix** [comment]
> We don't have custom model support directly in the randomizer. You can instead replace models yourself using regular mods and placing the files in the appropriate folder. If you're asking because of multiplayer, seeing other's own model is not supported.

Alr I thought there was compatibility due to tye custom_model files, thanks anyways
