### ISSUE TITLE
Door of Time not opening

### ISSUE THREAD

**Issue by BuffYoda21** [gamestabled/OoT3D_Randomizer#746]
I’m sure you’ve seen plenty of similar comments about similar issues and I have looked around at logic wikis and such and can’t figure it out. I started a game with the door of time closed and throughout the run I have obtained the ocarina and song of time (which the wiki said was all I needed) but the door didn’t open. So then I went out and grabbed the ocarina of time (not just fairy ocarina) and all three spiritual stones but the door still didn’t open. Help

**Comment by BuffYoda21** [comment]
Is there a flag or something for the end of each dungeon to trigger the next event like the DoT being able to open? I have deku tree and dodongo’s cavern finished but never found the boomerang to finish jabu jabu. Looked at the spoiler log and the boomerang is a gold skultula that only adult link can reach :/

**Comment by BuffYoda21** [comment]
Tried switching to Vanilla to play the song and that didn’t work either

**Comment by HylianFreddy** [comment]
Is the cutscene playing without the door opening? If so, you have to enter Temple of Time through the main entrance, not by playing prelude or save warping.

**Comment by BuffYoda21** [comment]
I entered through the main entrance and entrances are not randomized. As for the cutscene, it does not play one at all. He just plays the song then puts away the ocarina and nothing happens.

**Comment by Kewlan** [comment]
Could you send the spoiler log and a video of trying to unlock the door?

**Comment by BuffYoda21** [comment]
[1209092851 (Skull Token, Mask of Truth, Deku Nut, Boss Key, Frog)-spoilerlog (1).txt](https://github.com/user-attachments/files/16450025/1209092851.Skull.Token.Mask.of.Truth.Deku.Nut.Boss.Key.Frog.-spoilerlog.1.txt)
Github does not support .xml files so I changed the extension to .txt so I could send it. Feel free to change it back. As for the video I don't really have a good way to record my 3ds but what happens is basically what you'd expect to see if you just played SoT say in a random spot in hyrule field. No special sound effect upon taking out the ocarina signaling me to play a song to trigger something.

**Comment by Kewlan** [comment]
What wiki did you read? Regardless, the Door of Time is set to `Intended` which does mean you need Ocarina of Time and all three spiritual stones. Are you standing in the right place, in front of the altar, when playing the Song of Time?

**Comment by BuffYoda21** [comment]
![2024-08-01_02-20-34 950_bot](https://github.com/user-attachments/assets/fae4fc61-8f00-46eb-8a7b-8efd98b14162)
![2024-08-01_02-22-01 351_top](https://github.com/user-attachments/assets/b8c1f31d-6e48-4485-95fa-d5537200e0d4)
![2024-08-01_02-22-21 928_top](https://github.com/user-attachments/assets/6d1c6862-9456-43f8-a875-1bd7cd7b1165)
I think I am doing everything right. All stones and Oot, right spot (tried other locations too without luck), and SoT but no luck.

**Comment by Kewlan** [comment]
That certainly is odd. Did you create your save file before generating the seed? That causes many issues.

You're also using the old stable release from 2022. You can use the latest nightly build which has many bug fixes and features here: https://github.com/gamestabled/OoT3D_Randomizer/releases

**Comment by HylianFreddy** [comment]
I think in that screenshot you might be standing too far away from the pedestal. You should be close enough so that the A button says "Check".

**Comment by BuffYoda21** [comment]
No, I generated the seed then started a new game. I also didn't realize I was on an old version. As for the location I'm standing I don't think it is normally that picky but before I made this thread I had tried all around the ToT, including there, with no luck. If I update my randomizer version is there any way to save my file or do I have to start a new one?

**Comment by Kewlan** [comment]
You have to start anew.

**Comment by BuffYoda21** [comment]
Ok I will download the update and see if that fixes it, I will open a new issue if this happens again
