### ISSUE TITLE
Adult Trade Sequence Softlock(?)

### ISSUE THREAD

**Issue by BuffYoda21** [gamestabled/OoT3D_Randomizer#750]
Sorry in advance if this is just me not having proper game knowledge. Been playing an Oot3d rando and the ToT spiritual stone stand thing says that the spirit medallion is in kakariko village so I proceeded to do every check there but one where the lady in the potion shop normally sells the blue potion to you. I double checked the spoiler log (linked) and she does have the medallion but I can't figure out how to get it from her. Looked online and says I have to show the mushroom thing but that item was overwritten in my inventory long ago when I got the next trade item. Since, I have gone through every trade item and landed on the odd poultice. Am I screwed or is there a way to get the mushrooms back?

[1209092851 (Skull Token, Mask of Truth, Deku Nut, Boss Key, Frog)-spoilerlog (1).txt](https://github.com/user-attachments/files/16555761/1209092851.Skull.Token.Mask.of.Truth.Deku.Nut.Boss.Key.Frog.-spoilerlog.1.txt)

**Comment by PhlexPlexico** [comment]
Heya,

If you select the trade item in your inventory and press L or R it will shuffle through the trade items. Did you try doing this? 

Thanks!

**Comment by BuffYoda21** [comment]
Oh hey that worked thank you!
