### ISSUE TITLE
Door of Time Bug?

### ISSUE THREAD

**Issue by pullen8** [gamestabled/OoT3D_Randomizer#78]
This may just be a quirk of OoT3D that I am unaware of but I have obtained the Song of Time and played it at the Temple of Time as normal to open the door, but the door remains closed during and after the cutscene. The spiritual stones also conjoin together on the alter in one spot. Are the spiritual stones AND the Song of Time required to open the door instead of JUST the Song of Time in this version or is this a bug?

**Comment by gymnast86** [comment]
If you want to open the Door of Time you need to specifically enter through the entrance loading zone. If you spawn there as adult from a savewarp or enter the Temple of Time via the Prelude of Light, the Door of Time won't open during the cutscene. This is just how the base game works at the moment.

**Comment by pullen8** [comment]
Ah damn, I entered with Prelude of Light so I guess that means it's either restart or clip past the door (if that's even possible)?

**Comment by gymnast86** [comment]
To be more clear: It doesn't permanently prevent you from opening the Door of Time, you just need to exit and re-enter the Temple of Time through the front and then play the song again.
