### ISSUE TITLE
Ruto's Letter softlock

### ISSUE THREAD

**Issue by QuantumCarrot** [gamestabled/OoT3D_Randomizer#85]
Received Ruto's letter from the graveyard hookshot chest, and soon after found the Biggoron claim check in a chest on Death Mountain. However, upon getting the claim check the letter disappeared or was overwritten and now I can't get to Jabu Jabu.

Is there any in-game workaround for this or am I doomed to re-seed?

**Comment by SurrealShibe** [comment]
you can skip king zora using glitches

**Comment by gamestabled** [comment]
@QuantumCarrot Do you remember when this happened if you were playing with scrubsanity off, and if so did you ever purchase a potion from a vanilla business scrub? If so, it was likely that purchase which overwrote your ruto's letter. A fix for that bug with scrubs has now been pushed.

If that's not what happened, we are still a little stumped on why this issue occured. do you have any more info, maybe including the spoiler log from that playthrough?

**Comment by QuantumCarrot** [comment]
That sounds right, I didn't notice right away that the letter was gone and I'm pretty sure I had visited the potion scrubs at Zora's River. Thanks for the follow-up!
