### ISSUE TITLE
Kokiri Sword unequippable

### ISSUE THREAD

**Issue by AliasElInge** [gamestabled/OoT3D_Randomizer#88]
After going forward and backwards in time without getting the Kokiri Sword, the game puts Deku Sticks on my B button as child. After obtaining the Kokiri Sword as an adult and going back in time, the game "equips" the Kokiri Sword but Deku Sticks are still assigned to the B button with no way of selecting the Kokiri Sword and getting rid of the sticks.

**Comment by gymnast86** [comment]
This bug was fixed in the newest v1.0.2 release. You should be able to fix it in your playthrough by going between adult and child one more time though.
