### ISSUE TITLE
Mirrored world setting displays MQ's chest placement on maps

### ISSUE THREAD

**Issue by cedricviaccoz** [gamestabled/OoT3D_Randomizer#90]
I did a seed with vanilla dungeons, mirrored world setting set to "on", and with maps/compasses set to "Start With". All dungeons maps I've tested so far (DT, DC and Jabu's Belly) display the position of chests from the Master Quest version.

**Comment by gamestabled** [comment]
This is fixed now in the latest nightlies thanks to #136 and it will be included in any future release. Thanks for reporting it
