### ISSUE TITLE
It would be nice if the releases included a QR code for the 3dsx file 

### ISSUE THREAD

**Issue by TheBeardOfTruth** [gamestabled/OoT3D_Randomizer#95]
Mostly for easier installation using FBI, it's not *hard* to generate a QR code for those with the know-how but a lot of users might not know how.

Mostly just a QoL suggestion, not an issue with the randomizer per se but there's no other place to put suggestions about the releases either so /shrug.

**Comment by cjohnson57** [comment]
I'm not super familiar with the process but the QR codes link to something called Unistore which is where the generated .3dsx files are stored. As of right now it has to be updated manually. It may be possible to make a script that can do that automatically and I agree it would be very nice, but not as simple as generating a QR code.

**Comment by TheBeardOfTruth** [comment]
I mean, I just do it by generating a QR code for the file hosted @ the releases section, FBI doesn't really care where the URL points to, just that it points to somewhere.

I didn't really wanna go grab some screwdrivers just to get the sd card out, and I also didn't wanna type the url on the 3ds touch-keyboard (mostly because of this part:"1.0.2-056c32f0926376d79dd8185de38545bd59aa729f/OoT3D_Randomizer.3dsx")

I did check the universal updater to see if I could pull the randomizer with that but I didn't see it in the repo, maybe there's some other tool more suited that I'm unaware of but when I run out of ideas I throw FBI at the problem, that tends to solve it.
