### ISSUE TITLE
No Rainbow Bridge upon collecting all medaillons

### ISSUE THREAD

**Issue by Chrisco0801** [gamestabled/OoT3D_Randomizer#97]
So, after i have collected all the medaillons, and the light arrow cut scene, the bridge towards ganons castile does not appear.

**Comment by cjohnson57** [comment]
What did you set as your bridge requirement in your settings? If you set it as vanilla, you need shadow and spirit medallions + light arrows, so medallions aren't sufficient. (A spoiler log would be helpful.)

**Comment by gamestabled** [comment]
Going to close this with the assumption that your bridge was set to vanilla. Feel free to bring it back up if there is something wrong 👍

**Comment by Chrisco0801** [comment]
Sorry for not replying!

Yes, it was my own fault haha. Indeed vanilla settings!

Sorry!

Thanks for the amazing work.

Op wo 14 apr. 2021 om 08:05 schreef gamestabled ***@***.***>:
