### ISSUE TITLE
OoT3D Randomizer on Universal Updater

### ISSUE THREAD

**Issue by ghost** [gamestabled/OoT3D_Randomizer#98]
It would be nice to see the randomizer patcher in the Universal Updater DB, for easy updates and installs.

**Comment by PhlexPlexico** [comment]
Hey there, I think this already is in the Universal Updater - just in a different UniStore. It is in the resources channel within the discord, but if you would like, here is the current QR: 
![image](https://user-images.githubusercontent.com/3514085/114063926-5bd18800-9856-11eb-812f-9ee1cd356360.png)
