### ISSUE TITLE
Possible Logic Error relating to Fire Temple Small Keys

### ISSUE THREAD

**Issue by leggettc18** [gamestabled/OoT3D_Randomizer#99]
I was playing through version 1.0.2 of the randomizer and I seem to be stuck. The playthrough generated in the spoiler log has me getting my first progressive hookshot in the Fire Temple Compass Chest, however it is stuck behind a locked door, and all the fire temple keys I can find left in my spoiler log require the hookshot to obtain. [Spoiler Log](https://pastebin.com/2ErKZGZ2)

**Comment by cjohnson57** [comment]
You can get one from Volvagia. You can get to the boss room with the hover boots, which you have access to by that sphere.

**Comment by leggettc18** [comment]
Unfortunately I have already done that.

**Comment by cjohnson57** [comment]
My bad, that's a common mistake so I thought it was the issue. Is the only door you've yet to unlock the one in the fire maze? You can skip that key with hover boots.

**Comment by cjohnson57** [comment]
Actually, never mind, I think you're right- The logic only expects 5 keys to get to that chest but you need 6. Thanks for the report

**Comment by leggettc18** [comment]
You're good, the only way you'd know for sure is if I told you. I also haven't unlocked the door that leads to the fire maze. On the side in the room where the fire wall chases you. I think I already double checked all the fire key locations in the spoiler log that I have access to but I'll double check those locations in game tonight.

**Comment by leggettc18** [comment]
Oh ok, well if you're sure there's a logic error there then I'll just wait for next release. I might still triple check the key locations tonight just to ease my curiosity.

**Comment by cjohnson57** [comment]
Yeah, looking at your spoiler unfortunately I think your seed will be unbeatable without glitches due to this error, sorry about that. But if you want to try glitches, you can join the discord, plenty of people there would be willing to help you with them.

**Comment by leggettc18** [comment]
It's no big loss, I'll probably just wait until the gets merged.
